version: '3'

services:

  mysql:
    image: "mysql:5"
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"

  amqp:
    image: "rabbitmq:3-management"
    ports:
      - "5672:5672"
      - "15672:15672"

#  server:
#    build: .
#    ports:
#      - "8000:8000"
#    volumes:
#      - /c/Perfil/PhpstormProjects/skeleton:/var/www/
