version: '3'

services:

  mysql:
    image: "mysql:5"
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"

  amqp:
    image: "rabbitmq:3-management"
    ports:
      - "5672:5672"
      - "15672:15672"

  server-8000:
    image: "driftphp/base"
    ports:
      - "8000:8000"
    volumes:
      - /c/Perfil/PhpstormProjects/driftphp-skeleton:/var/www
    command: "php vendor/bin/server watch 0.0.0.0:8000 --exchange=my_events"

  server-8001:
    image: "driftphp/base"
    ports:
      - "8001:8001"
    volumes:
      - /c/Perfil/PhpstormProjects/driftphp-skeleton:/var/www
    command: "php vendor/bin/server watch 0.0.0.0:8001 --exchange=my_events"

  wbs-server:
    image: "driftphp/base"
    ports:
      - "9009:9009"
    volumes:
      - /c/Perfil/PhpstormProjects/driftphp-skeleton:/var/www
#      - /c/Perfil/PhpstormProjects/driftphp-skeleton/ws-var:/var/www/var
    command: "bin/console websocket:run 0.0.0.0:9009 --route=events --exchange=my_events"
