# Routes
default:
  path: /
  controller: App\Controller\DefaultController

get-user:
  path: /users/{uid}
  methods:
    - GET
  controller: App\Controller\GetUserController

put-user:
  path: /users/{uid}
  methods:
    - PUT
  controller: App\Controller\PutUserController
