# Routes
get-user:
  path: /users/{uid}
  methods:
    - GET
  controller: App\Controller\GetUserController

put-user:
  path: /users/{uid}
  methods:
    - PUT
  controller: App\Controller\PutUserController

delete-user:
  path: /users/{uid}
  methods:
    - DELETE
  controller: App\Controller\DeleteUserController
