parameters:
    kernel.secret: yoursecretshouldbehere
    app_path: "../.."

framework:
    form: false
    assets: false
    session: false
    translator: false
    php_errors:
        log: false

command_bus:
    query_bus:
    command_bus:
        middlewares:
            - Domain\Middleware\CheckUserNameLength

# config/services.yaml
services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    #
    # Controllers
    #
    App\Controller\:
        resource : "%app_path%/src/Controller/*"
        tags:
            - {name: controller.service_arguments}

    #
    # Command handlers
    #
    Domain\CommandHandler\:
        resource : "%app_path%/src/Domain/CommandHandler"
        tags:
            - { name: command_handler }

    #
    # Query handlers
    #
    Domain\QueryHandler\:
        resource : "%app_path%/src/Domain/QueryHandler"
        tags:
          - { name: query_handler }

    #
    # Middlewares
    #
    Domain\Middleware\:
        resource : "%app_path%/src/Domain/Middleware"


    #
    # Defino qué implementación usar para el repo
    #
    Domain\Model\User\InMemoryUserRepository:
    Domain\Model\User\UserRepository:
        alias: Domain\Model\User\InMemoryUserRepository
