parameters:
    kernel.secret: yoursecretshouldbehere
    app_path: "../.."

framework:
    form: false
    assets: false
    session: false
    translator: false
    php_errors:
        log: false

command_bus:
    query_bus:
    command_bus:
        middlewares:
            - Domain\Middleware\CheckUserNameLength

event_bus:
  exchanges:
    my_events: events_amqp
  router:
    _all: my_events
  async_pass_through: false
  async_adapter:
    adapter: amqp
    amqp:
      host: 192.168.1.143

dbal:
  connections:
    main:
      driver: mysql
      host: 192.168.1.143
      port: 3306
      user: root
      password: root
      dbname: usersdb

websocket:
  routes:
    events:
      path: /events
    other-events:
      path: /other-events


# config/services.yaml
services:
    _defaults:
        autowire: true
        autoconfigure: true
        public: true

    #
    # Controllers
    #
    App\Controller\:
        resource : "%app_path%/src/Controller/*"
        tags:
            - {name: controller.service_arguments}

    #
    # Command handlers
    #
    Domain\CommandHandler\:
        resource : "%app_path%/src/Domain/CommandHandler"
        tags:
            - { name: command_handler }

    #
    # Query handlers
    #
    Domain\QueryHandler\:
        resource : "%app_path%/src/Domain/QueryHandler"
        tags:
          - { name: query_handler }

    #
    # Middlewares
    #
    Domain\Middleware\:
        resource : "%app_path%/src/Domain/Middleware"


    #
    # Implementation to use for UserRepository
    #
    Domain\Model\User\InMemoryUserRepository:
    Domain\Model\User\ComposedUserRepository:
    Infrastructure\DBAL\Model\User\DBALUserRepository:
    Domain\Model\User\UserRepository:
        alias: Domain\Model\User\ComposedUserRepository
#        alias: Infrastructure\DBAL\Model\User\DBALUserRepository
#        alias: Domain\Model\User\InMemoryUserRepository

    Domain\Model\User\PersistentUserRepository:
        alias: Infrastructure\DBAL\Model\User\DBALUserRepository
